### PR TITLE
Modify the way files paths/URLs/schemes are handled

### LINKED ISSUE #1036: riff system install fails to install using manifest from local directory on Windows
To reproduce this, download a riff manifest and the corresponding kubernetes configuration files so that `manifest.yaml` looks something like this:
```
manifestVersion: "0.1"
istio:
- istio-riff-knative-serving-v0-2-3.yaml
knative:
- release.yaml
- serving.yaml
- eventing.yaml
- in-memory-channel.yaml
namespace:
- riff-cnb-buildtemplate-0.1.0.yaml
```
Notice that the kubernetes configuration files are referenced using relative file paths rather than URLs. These files are in the same directory as the manifest.

With this in place, issue the following from a Windows command prompt:
```
riff system install -m file:///C:\path\to\manifest\manifest.yaml
```

The failure is as follows:
```
Istio is already installed, do you want to install the Knative components for riff? [y/N]: y
Waiting for the Istio components to start . all components are 'Running'

Installing Knative components
Error applying resources, trying again

Error: open file:\C:\path\to\manifest\release.yaml: The filename, directory name, or volume label syntax is incorrect.
```

### PR DESCRIPTION
**Pull request by trisberg**
- on Windows using net/url.Parse with an absolute file path without a scheme but with a drive letter will cause the URL to report the drive letter as the scheme

Fixes #1036

### CODE REVIEW

File: pkg/fileutils/read.go [hunk 1]
```diff
@@ -38,17 +39,22 @@ func Read(file string, base string) ([]byte, error) {
...
 	u, err := url.Parse(file)
 	if err != nil {
 		return nil, err
 	}
-	if u.Scheme == "" {
+	if u.Scheme == "http" || u.Scheme == "https" || u.Scheme == "file" {
+		return ReadUrl(u, 0)
+	}
+	// On Windows the URL potentially ends up with the drive letter as the scheme so compare with the URL as a string
+	if u.Scheme == "" || (runtime.GOOS == "windows" && len(u.Scheme) == 1 && strings.HasPrefix(u.String(), u.Scheme + ":")) {
```
Comment (fbiville) [inline pkg/fileutils/read.go]: Nit: maybe extract the Windows-specific check in a small aptly-named function?

I was initially tempted to check that `u.Scheme` belongs to [a-z], but today I learnt that Windows XP (and later versions) supports mounting non-letter drives ([source](https://en.wikipedia.org/wiki/Drive_letter_assignment#Common_assignments)).

File: pkg/fileutils/read.go [hunk 2]
```diff
@@ -38,17 +39,21 @@ func Read(file string, base string) ([]byte, error) {
...
+	// The file argument could be an abs file reference or a URL
 	u, err := url.Parse(file)
 	if err != nil {
 		return nil, err
 	}
-	if u.Scheme == "" {
+	if u.Scheme == "http" || u.Scheme == "https" || u.Scheme == "file" {
+		return ReadUrl(u, 0)
+	}
+	if u.Scheme == "" || onWindowsSchemeIsDriveLetter(u) {
```
Comment (glyn) [inline pkg/fileutils/read.go]: I think this disjunction should be factored out into a helper function called something like `emptyScheme` because that's really what we are looking for. That will also make the caller more self-documenting.

File: pkg/fileutils/read.go [hunk 3]
```diff
@@ -94,3 +99,12 @@ func downloadFile(url string, timeout time.Duration) ([]byte, error) {
 	}
 	return buf.Bytes(), nil
 }
+
+func onWindowsSchemeIsDriveLetter(u *url.URL) bool {
+	// On Windows the URL potentially ends up with the drive letter as the scheme so compare with the URL as a string
+	if runtime.GOOS == "windows" && len(u.Scheme) == 1 && strings.HasPrefix(u.String(), u.Scheme + ":") {
```
Comment (glyn) [inline pkg/fileutils/read.go]: Doesn't `len(u.Scheme) == 1` _imply_ that `strings.HasPrefix(u.String(), u.Scheme + ":")`? If not, we need some testcases which show why this extra conjunct is needed.

Actually, more tests in this area, to cover the Windows novelties are probably advisable anyway, like Florian said.

Comment (ericbottard) [reply pkg/fileutils/read.go]: Even, isn't `strings.HasPrefix(u.String(), u.Scheme + ":")` ALWAYS true? This is just testing that a URL starts with its scheme followed by a colon. I don't think there is a 100% sure way to test this (there could always be a fancy scheme named "d"), but testing Windows + 1 letter scheme seems to be the best we can do for now

**Comment by glyn** [comment]
@trisberg BTW I really appreciate you coming to help with the delicate area of URL and file path handling in Go. The more eyes on this code, the better!

File: pkg/fileutils/read.go (hunk 3 above)
Comment (trisberg) [reply pkg/fileutils/read.go]: Looking at the whole chain the manifest file reference goes through, it seems we massage the path and strip out the scheme from the file reference, then we parse it into a URL again in this function, so now something like `C:/foo/bar.yaml` gets parsed as a scheme of `c` and a path of `/foo/bar.yaml` and a file like `C:\foo\bar.yaml` gets a scheme of `c` and and empty path. Lots of weird issues but this fix fixes some. And, yeah, we probably don't need the prefix test as long as the scheme is 1 character.

File: pkg/fileutils/read_test.go [hunk 4]
```diff
@@ -204,67 +204,76 @@ var _ = Describe("ReadUrl", func() {
...
 	var (
+		file	string
 		u       *url.URL
+		os      string
 		err     error
 		empty   bool
 	)
 
+	BeforeEach(func() {
+		os = "linux"
```
Comment (glyn) [inline pkg/fileutils/read_test.go]: It would be good to put this in a "linux" Context and have a corresponding "windows" context. Then it will be easier to compare which tests are run for which OS's.

File: pkg/fileutils/read_test.go [hunk 5]
```diff
@@ -275,7 +284,7 @@ var _ = Describe("EmptyScheme", func() {
 
 		It("scheme should not be empty", func() {
 			Expect(err).NotTo(HaveOccurred())
-			Expect(!empty)
+			Expect(empty).NotTo(BeTrue())
```
Comment (glyn) [inline pkg/fileutils/read_test.go]: `Expect(empty).To(BeFalse())` is easier to read.

File: pkg/fileutils/read_test.go [hunk 6]
```diff
@@ -204,67 +204,76 @@ var _ = Describe("ReadUrl", func() {
...
 	Context("when http: is the scheme", func() {
 		BeforeEach(func() {
-			u, err = url.Parse("http://foo.com/bar")
+			file = "http://foo.com/bar"
 		})
 
 		It("scheme should not be empty", func() {
 			Expect(err).NotTo(HaveOccurred())
-			Expect(!empty)
+			Expect(empty).NotTo(BeTrue())
```
Comment (glyn) [inline pkg/fileutils/read_test.go]: `Expect(empty).To(BeFalse())` is easier to read.

File: pkg/fileutils/read_test.go [hunk 7]
```diff
@@ -204,67 +204,76 @@ var _ = Describe("ReadUrl", func() {
...
 	Context("when file: is the scheme and using unix separators", func() {
 		BeforeEach(func() {
-			u, err = url.Parse("file:///my/file")
+			file = "file:///my/file"
 		})
 
 		It("scheme should not be empty", func() {
 			Expect(err).NotTo(HaveOccurred())
-			Expect(!empty)
+			Expect(empty).NotTo(BeTrue())
```
Comment (glyn) [inline pkg/fileutils/read_test.go]: `Expect(empty).To(BeFalse())` is easier to read.

File: pkg/fileutils/read_test.go [hunk 8]
```diff
@@ -254,10 +248,57 @@ var _ = Describe("EmptyScheme", func() {
...
+		})
+
+		It("scheme should not be empty", func() {
+			Expect(err).NotTo(HaveOccurred())
+			Expect(empty).To(BeFalse())
+		})
+	})
+})
+
+var _ = Describe("EmptyScheme on Unix-style OS", func() {
```
Comment (glyn) [inline pkg/fileutils/read_test.go]: This should be part of a single "EmptyScheme" Describe block with two Context blocks for macOS and linux, respectively. That will stop the two Describe blocks "parting company".

**Comment by trisberg** [comment]
rebased and squashed
