### PR TITLE
Avoid nil ListerWatcher in tail tests

### LINKED ISSUE #1326: Panic in github.com/projectriff/riff/pkg/riff/commands.Test*CreateCommand tail logs
https://dev.azure.com/projectriff/projectriff/_build/results?buildId=1512&view=logs&jobId=3d7fffa5-651a-5034-a012-b05135f8d9bc&taskId=2aff140a-4300-5bb0-6700-e65b0ea7f540&lineStart=652&lineEnd=653&colStart=1&colEnd=1

```
=== RUN   TestFunctionCreateCommand/tail_logs
E0612 15:10:32.887378   12662 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/opt/hostedtoolcache/go/1.12.0/x64/src/runtime/panic.go:522
/opt/hostedtoolcache/go/1.12.0/x64/src/runtime/panic.go:82
/opt/hostedtoolcache/go/1.12.0/x64/src/runtime/signal_unix.go:390
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:178
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:133
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:132
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54
/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/opt/hostedtoolcache/go/1.12.0/x64/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x100bd7d]

goroutine 615 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x169
panic(0x1e94240, 0x340e8e0)
	/opt/hostedtoolcache/go/1.12.0/x64/src/runtime/panic.go:522 +0x1b5
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0000e00a0, 0xc0001b0120, 0x0, 0x0)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:178 +0x25d
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:133 +0x4b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004bdf08)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x62
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000481f08, 0x3b9aca00, 0x0, 0x7f03af8cc601, 0xc0001b0120)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0x109
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0000e00a0, 0xc0001b0120)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/client-go/tools/cache/reflector.go:132 +0x1dd
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:54 +0x46
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00053e810, 0xc0002c6160)
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x5d
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/home/vsts/work/1/s/projectriff/riff/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x70
FAIL	github.com/projectriff/riff/pkg/riff/commands	1.297s
```

### PR DESCRIPTION
**Pull request by scothis**
Fixes #1326

### CODE REVIEW

File: pkg/k8s/wait.go [hunk 1]
```diff
@@ -42,7 +42,12 @@ type object interface {
 
 // WaitUntilReady watches for mutations of the target object until the target is ready.
 func WaitUntilReady(ctx context.Context, client rest.Interface, resource string, target object) error {
-	lw := GetListWatch(ctx, client, resource, target)
+	lw := GetListerWatcher(ctx, client, resource, target)
+	if lw == nil {
+		// the ListerWatcher can be nil for tests, simulate waiting by blocking
```
Comment (ericbottard) [inline pkg/k8s/wait.go]: Can't this return an implementation that does the blocking instead? (ie don't make the caller aware of the special case)?

Comment (scothis) [reply pkg/k8s/wait.go]: This is a work in progress. I pushed it up to see if the CI would be happy.

Comment (scothis) [reply pkg/k8s/wait.go]: done
