### PR TITLE
Fix tests on Windows

### LINKED ISSUE #1174: Tests fail on Windows
If I run `make` the tests fail with:

```
$ make
GO111MODULE=on go test ./...
can't load package: package github.com/projectriff/riff:
main.go:1:1: expected 'package', found cmd
make: *** [Makefile:19: test] Error 1
```

Modifying `Makefile` to use `GO111MODULE=on go test ./pkg/...` and applying #1173 -  I see the following errors:

```
Summarizing 4 Failures:

[Fail] namespace NamespaceInit [It] should create secret for gcr
C:/Users/trisberg/workspace/projectriff/riff/pkg/core/namespace_test.go:132

[Panic!] namespace NamespaceInit [It] should apply label to namespace resources
C:/Go/src/runtime/panic.go:513

[Panic!] namespace NamespaceInit [It] should fail if the PVC label kustomization fails
C:/Go/src/runtime/panic.go:513

[Panic!] namespace NamespaceInit [It] should support local kubernetes configuration files
C:/Go/src/runtime/panic.go:513

Ran 67 of 67 Specs in 0.241 seconds
FAIL! -- 63 Passed | 4 Failed | 0 Pending | 0 Skipped



Summarizing 2 Failures:

[Fail] Kustomize wrapper [It] customizes remote resources with provided labels
C:/Users/trisberg/workspace/projectriff/riff/pkg/core/kustomize/kustomize_test.go:92

[Fail] Kustomize wrapper [It] customizes local resources with provided labels
C:/Users/trisberg/workspace/projectriff/riff/pkg/core/kustomize/kustomize_test.go:102

Ran 5 of 5 Specs in 1.048 seconds
FAIL! -- 3 Passed | 2 Failed | 0 Pending | 0 Skipped



Summarizing 1 Failure:

[Fail] ResolveTilde [It] resolves ~/ against current user's home directory
C:/Users/trisberg/workspace/projectriff/riff/pkg/fileutils/paths_test.go:61

Ran 59 of 59 Specs in 0.286 seconds
FAIL! -- 58 Passed | 1 Failed | 0 Pending | 0 Skipped
```

### PR DESCRIPTION
**Pull request by trisberg**
Fixes #1174

### CODE REVIEW

**Comment by scothis** [comment]
I updated the pipeline to force Windows tests to pass. Looks like there are still some failures

**Comment by sbawaska** [comment]
I am working on an issue in go-ape where "d:" is not recognized as a scheme, which is somewhat related to this.

**Comment by trisberg** [comment]
I don't know what to make of those test failures. It works on my Windows machine. I even set up a D: drive to test it:

```
PS D:\a\1\s\projectriff\riff> go test ./...
?       github.com/projectriff/riff/cmd/riff    [no test files]
ok      github.com/projectriff/riff/pkg/core    1.152s
ok      github.com/projectriff/riff/pkg/core/kustomize  1.284s
?       github.com/projectriff/riff/pkg/core/kustomize/mocks    [no test files]
?       github.com/projectriff/riff/pkg/core/mocks      [no test files]
?       github.com/projectriff/riff/pkg/core/mocks/mockbuilder  [no test files]
ok      github.com/projectriff/riff/pkg/core/tasks      0.829s [no tests to run]
?       github.com/projectriff/riff/pkg/core/vendor_mocks       [no test files]
?       github.com/projectriff/riff/pkg/core/vendor_mocks/mockbuild     [no test files]
?       github.com/projectriff/riff/pkg/core/vendor_mocks/mockserving   [no test files]
?       github.com/projectriff/riff/pkg/env     [no test files]
ok      github.com/projectriff/riff/pkg/fileutils       1.206s
?       github.com/projectriff/riff/pkg/fileutils/mocks [no test files]
?       github.com/projectriff/riff/pkg/kubectl [no test files]
?       github.com/projectriff/riff/pkg/kubectl/mocks   [no test files]
?       github.com/projectriff/riff/pkg/osutils [no test files]
ok      github.com/projectriff/riff/pkg/riff/commands   2.102s
?       github.com/projectriff/riff/pkg/test_support    [no test files]
```

**Comment by sbawaska** [comment]
Please see: https://github.com/pivotal/go-ape/pull/11/commits/2bfb4c0b0ecf7581776c6254ad753fba6ad7d663
Once that PR is merged, we should get that fix here.

**Comment by trisberg** [comment]
What is the difference between the CI environment and my Windows 10 install? I don't see this issue on the latter.

**Comment by scothis** [comment]
Looks like https://github.com/projectriff/riff/blob/1376aee9f976a243d60e6a2e6e75587383a19ecb/pkg/core/manifest_test.go#L41 is returning errors we didn't anticipate, meaning the manifest to be nil and causing nil dereference panics.

**Comment by trisberg** [comment]
rebased

File: pkg/core/namespace_test.go [hunk 1]
```diff
@@ -134,7 +136,13 @@ var _ = Describe("namespace", func() {
 			mockSecrets.On("Create", mock.Anything).Run(func(args mock.Arguments) {
 				s := args[0].(*v1.Secret)
 				Expect(s.StringData).To(HaveKeyWithValue("username", "_json_key"))
-				Expect(s.StringData).To(HaveKeyWithValue("password", "{ \"project_id\": \"gcp-project-id\" }\n"))
+				var expectedPassword string
```
[the remark this answers is not in the document]
Comment (scothis) [reply pkg/core/namespace_test.go]: That won't work since the HaveKeyWithValue matcher uses Equals internally.

Rather than redefining the value, we could wrap it in a method that replaced `\n` with `\r\n` based on the platform.

File: pkg/core/namespace_test.go [hunk 2]
```diff
@@ -646,7 +653,17 @@ func keys(keys ...string) func(dict map[string]string) bool {
 
 func urlPath(path string) func(url *url.URL) bool {
 	return func(url *url.URL) bool {
-		return url.Path == path
+		if runtime.GOOS == "windows" && len(url.Scheme) == 1 {
```
Comment (scothis) [inline pkg/core/namespace_test.go]: @sbawaska is there something in go-ape for this? If not, should there be?

Comment (sbawaska) [reply pkg/core/namespace_test.go]: There is, but is is private: https://github.com/pivotal/go-ape/blob/master/pkg/furl/read.go#L55

Comment (trisberg) [reply pkg/core/namespace_test.go]: I had to add some code to handle letters which seems to vary between `D:` vs `d:`, maybe depending on some OS setting or type of filesystem. Not sure why that is, but I had to check the case of the drive letter part of the expected path to be able to match it.
